### ISSUE TITLE
Advanced search is impossible on branch 3.14.x

### ISSUE THREAD

**Issue by gjoncour** [ebsco/edsapi-koha-plugin#3]
Hi,

We recently install EDSAPI-Koha plugin on our 3.14.11 Koha instance. Unfortunately, advanced search seems to be impossible : pressing search button returns a JS alert saying *"Please enter a valid year in YYYY format"*.
After a quick look in **EDSScript.js**, this message is sent when **#common_DT1_ToYear** or **#common_DT1_FromYear** values aren't numeric. However, these fields, presents on master branch, are replaced by a single field without id attribute accepting *YYYY-MM/YYYY-MM* period form.

Could you please revert EDSScript.js to a functional state or evolve the advanced search on 3.14.x branch to master/3.16.x state ?
Thank you,

Gwendal JONCOUR

**Comment by alvetm** [comment]
This was a known issue and is fixed in v 1.82 of the plugin (bootstrap template). What OPAC template do you use for Koha? Prog?

If so adding the below code block at the end of eds-advsearch.tt should fix the problem till a new version is available.

<script>
	$('[placeholder]').focus(function() {
	  var input = $(this);
	  if (input.val() == input.attr('placeholder')) {
		input.val('');
		input.removeClass('placeholder');
	  }
	}).blur(function() {
	  var input = $(this);
	  if (input.val() == '' || input.val() == input.attr('placeholder')) {
		input.addClass('placeholder');
		input.val(input.attr('placeholder'));
	  }
	}).blur();
// 	required for EDS date funciton to work
</script>

**Comment by gjoncour** [comment]
Replace input's value by his placeholder didn't fix the problem since tested field isn't present in the prog theme of the plugin.
I'll try to resolve it by myself, I just wanted to declare this issue for others using prog theme on Koha 3.14.

Thank you for yout quick answer.

**Comment by alvetm** [comment]
Cool - thanks. The prog block still has Koha v3.12 code in there and wasnt updated in v 1.7+ for Koha v3.14 since all users at the time had moved to bootstrap.
It is updated for Koha v3.16. It would be great if you could share your changes to include in this repository.

**Comment by alvetm** [comment]
No plans to update the prog them as it is removed from Koha.
